//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sge.persistance.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SGS_dbContainer : DbContext
    {
        public SGS_dbContainer()
            : base("name=SGS_dbContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Formations> Formations1 { get; set; }
        public virtual DbSet<Cours> Cours { get; set; }
        public virtual DbSet<Enseignants> Enseignants { get; set; }
        public virtual DbSet<Etudiants> Etudiants { get; set; }
        public virtual DbSet<Sessions> Sessions1 { get; set; }
        public virtual DbSet<CoursFormations> CoursFormations { get; set; }
        public virtual DbSet<Inscriptions> Inscriptions { get; set; }
    }
}
